window.pagesData = [
  { page: 1, title: "Cover", chapter: 0, searchText: "How Google Works Eric Schmidt Jonathan Rosenberg Alan Eagle" },
  { page: 2, title: "Title Page", chapter: 0, searchText: "How Google Works Eric Schmidt Jonathan Rosenberg Alan Eagle Grand Central Publishing" },
  { page: 3, title: "Copyright Page", chapter: 0, searchText: "copyright Hachette Book Group Grand Central Publishing scanning uploading electronic sharing" },
  { page: 4, title: "Dedication", chapter: 0, searchText: "dedication favorite smart creatives Wendy Beryl" },
  { page: 5, title: "Illustration - Smart Creatives", chapter: 0, searchText: "illustration smart creatives cartoon" },
  { page: 6, title: "Foreword by Larry Page", chapter: 0, searchText: "Larry Page foreword introduction Google uncommon uncomfortably exciting" },
  { page: 7, title: "Foreword by Larry Page (continued)", chapter: 0, searchText: "Larry Page foreword technology positive force billion people coach thank you" },
  { page: 8, title: "Introduction - Lessons Learned from the Front Row", chapter: 1, searchText: "Introduction Lessons Learned Front Row Finland email Mike Moritz Sequoia Capital" },
  { page: 9, title: "The Finland Email", chapter: 1, searchText: "Finland plan Eric Schmidt mobile internet strategy Symbian Nokia" },
  { page: 10, title: "Eric's Background at Google", chapter: 1, searchText: "Eric Schmidt CEO Novell Google Larry Page Sergey Brin John Doerr board interview" },
  { page: 11, title: "Just Go Talk to the Engineers", chapter: 1, searchText: "talk to engineers Eric office cubicle building 43 technical discussions ads suck" },
  { page: 12, title: "The Finland Plan", chapter: 1, searchText: "Finland plan strategy mobile platforms Microsoft Windows operating system disruption" },
  { page: 13, title: "When Astonishing Isn't", chapter: 1, searchText: "astonishing technology Internet Century transformation disruption change speed" },
  { page: 14, title: "The Speed of Change", chapter: 1, searchText: "speed technology change computing power Moore's Law Internet Century smartphones" },
  { page: 15, title: "The Internet Century", chapter: 1, searchText: "Internet Century information technology cloud computing smartphones global connectivity bandwidth" },
  { page: 16, title: "The Smart Creative", chapter: 1, searchText: "smart creative knowledge worker technical expertise business savvy creativity Peter Drucker" },
  { page: 17, title: "Defining the Smart Creative", chapter: 1, searchText: "smart creative deep technical knowledge hands-on risk-taker self-directed creative curious" },
  { page: 18, title: "A Fun Project for the Two of Us", chapter: 1, searchText: "Eric Jonathan book project Rachel Whetstone email fun project management lessons" },
  { page: 19, title: "A Fun Project (continued)", chapter: 1, searchText: "book project management lessons Google how companies should run smart creatives attract" },
  { page: 20, title: "Pyramids Unbuilt", chapter: 1, searchText: "pyramids management traditional hierarchy twentieth century corporation industrial era" },
  { page: 21, title: "Pyramids Unbuilt (continued)", chapter: 1, searchText: "management hierarchy Internet Century smart creatives empowerment speed innovation" },
  { page: 22, title: "How Google Works Overview", chapter: 1, searchText: "culture strategy talent decisions communications innovation overview book structure" },
  { page: 23, title: "Book Structure and Approach", chapter: 1, searchText: "book structure chapters culture strategy talent decisions communications innovation conclusion" },
  { page: 24, title: "Our Perspective", chapter: 1, searchText: "Eric Jonathan perspective Google lessons management business Alan Eagle coauthor" },
  { page: 25, title: "Introduction Conclusion", chapter: 1, searchText: "introduction conclusion smart creatives manage differently Internet Century begin" },
  { page: 26, title: "Culture - Believe Your Own Slogans", chapter: 2, searchText: "Culture Believe Your Own Slogans these ads suck Larry Page AdWords kitchen" },
  { page: 27, title: "These Ads Suck", chapter: 2, searchText: "ads suck Larry Page kitchen bulletin board AdWords quality problem engineers weekend fix" },
  { page: 28, title: "Culture Eats Strategy", chapter: 2, searchText: "culture eats strategy Peter Drucker culture strategy breakfast importance values" },
  { page: 29, title: "Culture Matters", chapter: 2, searchText: "culture matters IPO founders letter Larry Sergey don't be evil values principles" },
  { page: 30, title: "IPO Letter and Culture", chapter: 2, searchText: "IPO letter Google founders culture values long-term focus not conventional company" },
  { page: 31, title: "Keep Them Crowded", chapter: 2, searchText: "keep them crowded office space interaction collaboration cramped quarters offices" },
  { page: 32, title: "Work Eat and Live Together", chapter: 2, searchText: "work eat live together offices cafes collaboration Yahoo Marissa Mayer working from home" },
  { page: 33, title: "Messiness as Virtue", chapter: 2, searchText: "messiness offices cluttered creative environment self-expression personal touches cubicles" },
  { page: 34, title: "Your Parents Were Wrong", chapter: 2, searchText: "parents were wrong messy offices creative work environment Google express yourself" },
  { page: 35, title: "Don't Listen to HiPPOs", chapter: 2, searchText: "HiPPO Highest Paid Person's Opinion data meritocracy decisions best idea wins" },
  { page: 36, title: "The Rule of Seven", chapter: 2, searchText: "rule of seven management span of control direct reports organizational structure flat" },
  { page: 37, title: "Every Tub on Its Own Bottom", chapter: 2, searchText: "every tub own bottom organizational structure functional not business units engineering product" },
  { page: 38, title: "Do All Reorgs in a Day", chapter: 2, searchText: "reorgs reorganization one day quick change organizational structure speed agility" },
  { page: 39, title: "The Bezos Two-Pizza Rule", chapter: 2, searchText: "Bezos two-pizza rule small teams Amazon Jeff Bezos team size communication" },
  { page: 40, title: "Organize Around Impact", chapter: 2, searchText: "organize around people impact highest engineering talent product development influence" },
  { page: 41, title: "Exile Knaves but Fight for Divas", chapter: 2, searchText: "exile knaves fight for divas brilliant jerks culture toxic behavior talented difficult" },
  { page: 42, title: "Overworked in a Good Way", chapter: 2, searchText: "overworked good way work-life balance smart creatives passion intensity burnout" },
  { page: 43, title: "Establish a Culture of Yes", chapter: 2, searchText: "culture of yes saying yes new ideas innovation bureaucracy no antibodies" },
  { page: 44, title: "Fun Not Fun", chapter: 2, searchText: "fun not Fun authentic culture forced fun organic humor memes spontaneous" },
  { page: 45, title: "Memes and Humor at Google", chapter: 2, searchText: "memes humor Memegen Google culture internal jokes satire commentary employees" },
  { page: 46, title: "You Must Wear Something", chapter: 2, searchText: "wear something dress code casual culture Google expression clothing" },
  { page: 47, title: "Changing Culture at Motorola", chapter: 2, searchText: "Motorola culture change dress code formality casual smart creatives acquisition" },
  { page: 48, title: "Ah'cha'rye - Follow Me", chapter: 2, searchText: "Ahcharye follow me leadership Hebrew Israeli army culture lead by example front" },
  { page: 49, title: "Don't Be Evil", chapter: 2, searchText: "don't be evil Google motto values ethics culture Paul Buchheit meaning" },
  { page: 50, title: "Don't Be Evil (continued)", chapter: 2, searchText: "don't be evil implementation values culture decisions ethics revenue trust users" },
  { page: 51, title: "Don't Be Evil in Practice", chapter: 2, searchText: "evil ethics culture values decisions trust employees autonomy canary coal mine" },
  { page: 52, title: "Culture and Values in Action", chapter: 2, searchText: "culture values mission statement authentic slogans Google principles believe" },
  { page: 53, title: "Culture Defines the Company", chapter: 2, searchText: "culture defines company believe slogans crowded offices meritocracy values" },
  { page: 54, title: "Culture Summary", chapter: 2, searchText: "culture summary small teams yes fun evil values principles flat organization" },
  { page: 55, title: "Culture Summary (continued)", chapter: 2, searchText: "culture summary leadership values principles Google lessons crowded messy" },
  { page: 56, title: "Culture Conclusion", chapter: 2, searchText: "culture conclusion believe your own slogans Google values authentic slogans" },
  { page: 57, title: "Strategy Chapter Illustration", chapter: 2, searchText: "illustration strategy chapter monkey bars cartoon" },
  { page: 58, title: "Strategy - Your Plan Is Wrong", chapter: 3, searchText: "Strategy Your Plan Is Wrong business plan venture capital technical insights" },
  { page: 59, title: "Strategy Chapter Opening", chapter: 3, searchText: "strategy plan wrong Eric Schmidt Google business plans disruption venture capital" },
  { page: 60, title: "Bet on Technical Insights", chapter: 3, searchText: "bet on technical insights innovation technology foundation product strategy novel" },
  { page: 61, title: "Technical Insights Defined", chapter: 3, searchText: "technical insights defined novel application technology problem solving cost reduction speed" },
  { page: 62, title: "Google Search Technical Insight", chapter: 3, searchText: "Google search PageRank technical insight Larry Page citation analysis web links ranking" },
  { page: 63, title: "Combinatorial Innovation", chapter: 3, searchText: "combinatorial innovation Hal Varian technologies components recombine new applications GPS" },
  { page: 64, title: "Don't Look for Faster Horses", chapter: 3, searchText: "faster horses Henry Ford customer research market insight innovation focus groups" },
  { page: 65, title: "Don't Look for Faster Horses (continued)", chapter: 3, searchText: "faster horses Steve Jobs consumer research technical insight innovation product vision" },
  { page: 66, title: "Optimize for Growth", chapter: 3, searchText: "optimize for growth revenue scaling platform strategy business model free products" },
  { page: 67, title: "Optimize for Growth (continued)", chapter: 3, searchText: "optimize growth scaling Google ads revenue free products platform global reach" },
  { page: 68, title: "Coase and the Nature of the Firm", chapter: 3, searchText: "Coase nature of the firm Ronald Coase transaction costs outsourcing Internet Nobel" },
  { page: 69, title: "Coase and Transaction Costs", chapter: 3, searchText: "Coase transaction costs firm size Internet Century specialization outsourcing cheap" },
  { page: 70, title: "Specialize", chapter: 3, searchText: "specialize niche focus expertise platform business strategy core competency" },
  { page: 71, title: "Specialize (continued)", chapter: 3, searchText: "specialize Google search focus core competency platform strategy excellence" },
  { page: 72, title: "Default to Open Not Closed", chapter: 3, searchText: "default to open open source platforms standards sharing collaboration ecosystem" },
  { page: 73, title: "Default to Open (continued)", chapter: 3, searchText: "open platforms standards Android open source ecosystem sharing innovation network effects" },
  { page: 74, title: "Default to Open Except When", chapter: 3, searchText: "open except closed proprietary advantage intellectual property trade secrets protect" },
  { page: 75, title: "Don't Follow Competition", chapter: 3, searchText: "don't follow competition strategy differentiation unique value proposition focus users" },
  { page: 76, title: "Don't Follow Competition (continued)", chapter: 3, searchText: "competition strategy Microsoft Google focus innovation users not competitors chasing" },
  { page: 77, title: "Eric's Strategy Notes", chapter: 3, searchText: "Eric strategy notes Google planning principles guidelines foundation growth" },
  { page: 78, title: "Strategy Planning Process", chapter: 3, searchText: "strategy planning process Google foundation plan technical insights platforms iteration" },
  { page: 79, title: "Strategy Planning (continued)", chapter: 3, searchText: "strategy planning growth platforms open innovation Eric notes guidelines" },
  { page: 80, title: "Building a Platform", chapter: 3, searchText: "platform building multisided market users developers ecosystem network effects scale" },
  { page: 81, title: "Platform Strategy", chapter: 3, searchText: "platform strategy multisided markets network effects Google Android YouTube search ads" },
  { page: 82, title: "New Ventures and Platforms", chapter: 3, searchText: "new ventures platforms start-ups disruption incumbents strategy technology" },
  { page: 83, title: "Look for Growth Markets", chapter: 3, searchText: "growth markets big market opportunity technology change disruption potential" },
  { page: 84, title: "Eric's Strategy Questions", chapter: 3, searchText: "strategy questions Eric Schmidt technology platforms what is different growth" },
  { page: 85, title: "Strategy and Iteration", chapter: 3, searchText: "strategy iteration adapt plans wrong adjust learn pivot flexible" },
  { page: 86, title: "Strategy and Planning", chapter: 3, searchText: "strategy planning adapt iterate Google approach business plans flexible" },
  { page: 87, title: "Strategy Summary", chapter: 3, searchText: "strategy summary technical insights growth open platforms competition" },
  { page: 88, title: "Strategy Lessons", chapter: 3, searchText: "strategy lessons plan is wrong bet technical insights optimize growth open" },
  { page: 89, title: "Strategy Continued", chapter: 3, searchText: "strategy continued platforms open closed ecosystems network effects" },
  { page: 90, title: "Strategy and Platforms", chapter: 3, searchText: "strategy platforms ecosystems network effects scale growth markets" },
  { page: 91, title: "Strategy and Markets", chapter: 3, searchText: "strategy markets growth disruption technology platforms competition" },
  { page: 92, title: "Strategy Notes", chapter: 3, searchText: "strategy notes Eric Schmidt planning guidelines principles Google business" },
  { page: 93, title: "Strategy and Business", chapter: 3, searchText: "strategy business plans market growth technology innovation adaptation" },
  { page: 94, title: "Strategy Closing", chapter: 3, searchText: "strategy closing plan wrong technical insights growth open platforms" },
  { page: 95, title: "Strategy Chapter End", chapter: 3, searchText: "strategy chapter end summary business plans technical insights growth" },
  { page: 96, title: "Strategy Final Page", chapter: 3, searchText: "strategy final page conclusion technical insights growth open" },
  { page: 97, title: "Talent Chapter Illustration", chapter: 3, searchText: "illustration talent chapter hiring people cartoon" },
  { page: 98, title: "Talent - Hiring Is the Most Important Thing You Do", chapter: 4, searchText: "Talent Hiring Most Important Thing Jonathan interview Sergey Brin Google" },
  { page: 99, title: "Jonathan's Interview with Sergey", chapter: 4, searchText: "Jonathan Rosenberg interview Sergey Brin hiring Google product management team building" },
  { page: 100, title: "The Herd Effect", chapter: 4, searchText: "herd effect hiring A players attract A players B players hire C players talent quality" },
  { page: 101, title: "The Herd Effect (continued)", chapter: 4, searchText: "herd effect talent quality breeds quality hiring standards bar excellence" },
  { page: 102, title: "Passionate People", chapter: 4, searchText: "passionate people hiring passion interest curiosity smart creatives drive" },
  { page: 103, title: "Passionate People (continued)", chapter: 4, searchText: "passion work hiring interesting people curious learning growth drive energy" },
  { page: 104, title: "Hire Learning Animals", chapter: 4, searchText: "hire learning animals growth mindset adaptability intelligence curiosity change" },
  { page: 105, title: "Learning Animals (continued)", chapter: 4, searchText: "learning animals hire ability to learn adapt change growth Coach Wooden UCLA" },
  { page: 106, title: "The LAX Test", chapter: 4, searchText: "LAX test airport hiring culture fit interesting conversation six hours stuck" },
  { page: 107, title: "Insight That Can't Be Taught", chapter: 4, searchText: "insight can't be taught innate analytical skill pattern recognition hire" },
  { page: 108, title: "Expand the Aperture", chapter: 4, searchText: "expand aperture hiring diverse backgrounds nontraditional candidates talent pool widen" },
  { page: 109, title: "Everyone Knows Someone Great", chapter: 4, searchText: "everyone knows someone great referrals hiring network employee referrals sourcing" },
  { page: 110, title: "Referral Hiring", chapter: 4, searchText: "referral hiring employee referrals network talent sourcing recruiting Google" },
  { page: 111, title: "Interviewing Skills", chapter: 4, searchText: "interviewing skills questions hiring assessment evaluation candidates structured" },
  { page: 112, title: "Interviewing at Google", chapter: 4, searchText: "interviewing Google process questions structured hiring committee assessment" },
  { page: 113, title: "Schedule Interviews for Thirty Minutes", chapter: 4, searchText: "thirty minute interviews scheduling efficiency hiring process time assessment" },
  { page: 114, title: "Have an Opinion", chapter: 4, searchText: "have an opinion interviewing hiring decision strong views assessment feedback" },
  { page: 115, title: "Friends Don't Let Friends Hire", chapter: 4, searchText: "friends hiring promotion committees peer review group decision quality control" },
  { page: 116, title: "Hiring Committees", chapter: 4, searchText: "hiring committees group decision peer review consensus quality control packets" },
  { page: 117, title: "Hiring Committees (continued)", chapter: 4, searchText: "hiring committees Google process review packets decisions quality bar standards" },
  { page: 118, title: "Urgency of Hiring", chapter: 4, searchText: "urgency hiring talent competition speed recruiting process efficiency pipeline" },
  { page: 119, title: "Disproportionate Rewards", chapter: 4, searchText: "disproportionate rewards compensation top performers unfair pay equity talent retain" },
  { page: 120, title: "Trading Players", chapter: 4, searchText: "trading players internal mobility transfers rotation talent development growth" },
  { page: 121, title: "Trading Players (continued)", chapter: 4, searchText: "trading players mobility internal transfers Google talent development freedom" },
  { page: 122, title: "If You Love Them Let Them Go", chapter: 4, searchText: "love them let them go retention mobility freedom smart creatives opportunities" },
  { page: 123, title: "Retention and Mobility", chapter: 4, searchText: "retention mobility keeping talent career growth development opportunities freedom" },
  { page: 124, title: "Firing", chapter: 4, searchText: "firing letting people go performance underperformers difficult decisions management" },
  { page: 125, title: "Firing (continued)", chapter: 4, searchText: "firing performance management underperformers Google process kindness dignity" },
  { page: 126, title: "How to Spot Talent", chapter: 4, searchText: "spot talent hiring signals character intelligence creativity passion curiosity" },
  { page: 127, title: "Googleyness", chapter: 4, searchText: "Googleyness hiring culture fit ambiguity comfort collaboration fun humility" },
  { page: 128, title: "Career Development", chapter: 4, searchText: "career development growth opportunities learning smart creatives progression skills" },
  { page: 129, title: "Career Advice - Statistics Is the New Plastics", chapter: 4, searchText: "career advice statistics new plastics data analytics skills graduate future" },
  { page: 130, title: "Statistics and Data Skills", chapter: 4, searchText: "statistics data skills analytics career future jobs technology importance" },
  { page: 131, title: "Make Your Elevator Pitch", chapter: 4, searchText: "elevator pitch career plan five words describe contribution unique value proposition" },
  { page: 132, title: "Go Abroad", chapter: 4, searchText: "go abroad international experience career global perspective travel cultural exposure" },
  { page: 133, title: "Combine Passion with Contribution", chapter: 4, searchText: "combine passion contribution career advice purpose meaningful work value" },
  { page: 134, title: "Career and Passion", chapter: 4, searchText: "career passion contribution meaningful work purpose smart creatives fulfillment" },
  { page: 135, title: "Your Career Choices", chapter: 4, searchText: "career choices decisions industry company role growth opportunity big vs small" },
  { page: 136, title: "Career Advice (continued)", chapter: 4, searchText: "career advice lessons talent growth development smart creatives trajectory" },
  { page: 137, title: "Choosing Companies", chapter: 4, searchText: "choosing companies career decisions industry growth opportunity team culture" },
  { page: 138, title: "Career Growth Path", chapter: 4, searchText: "career growth path development decisions industry company opportunity skills" },
  { page: 139, title: "Talent Principles", chapter: 4, searchText: "talent principles hiring passionate people learning animals committees referrals" },
  { page: 140, title: "Talent Summary", chapter: 4, searchText: "talent summary hiring committees referrals aperture diversity rewards mobility" },
  { page: 141, title: "Talent Dos and Don'ts", chapter: 4, searchText: "talent dos and don'ts hiring best practices committees quality standards" },
  { page: 142, title: "Talent Chapter Review", chapter: 4, searchText: "talent review hiring importance committees quality career advice Google" },
  { page: 143, title: "Talent Practices", chapter: 4, searchText: "talent practices hiring Google process lessons learned interview committees" },
  { page: 144, title: "Talent and Career", chapter: 4, searchText: "talent career development growth statistics elevator pitch abroad passion" },
  { page: 145, title: "Talent Best Practices", chapter: 4, searchText: "talent best practices hiring career advice statistics passion contribution" },
  { page: 146, title: "Talent Management", chapter: 4, searchText: "talent management hiring developing retaining smart creatives Google culture" },
  { page: 147, title: "Talent and People", chapter: 4, searchText: "talent people hiring managing developing smart creatives Google rewards" },
  { page: 148, title: "Talent Chapter Notes", chapter: 4, searchText: "talent notes hiring career Google smart creatives development growth" },
  { page: 149, title: "Talent and Retention", chapter: 4, searchText: "talent retention hiring lessons learned career development mobility freedom" },
  { page: 150, title: "Talent Chapter Closing", chapter: 4, searchText: "talent closing hiring managing people smart creatives culture quality" },
  { page: 151, title: "Coaching Introduction", chapter: 4, searchText: "coaching introduction leadership mentorship Bill Campbell management development" },
  { page: 152, title: "Bill Campbell - The Coach", chapter: 4, searchText: "Bill Campbell coach leadership mentorship Google Apple Silicon Valley trust" },
  { page: 153, title: "Coaching by Bill Campbell", chapter: 4, searchText: "coaching Bill Campbell trillion dollar coach management mentorship guidance" },
  { page: 154, title: "Bill Campbell and Leadership", chapter: 4, searchText: "Bill Campbell coaching leadership mentorship Google Apple Columbia football" },
  { page: 155, title: "The Value of Coaching", chapter: 4, searchText: "coaching value leadership development Bill Campbell mentorship growth improvement" },
  { page: 156, title: "Coaching Lessons", chapter: 4, searchText: "coaching lessons Bill Campbell leadership mentor development growth self-review" },
  { page: 157, title: "Decisions Chapter Illustration", chapter: 4, searchText: "illustration decisions chapter consensus meeting cartoon" },
  { page: 158, title: "Decisions - The True Meaning of Consensus", chapter: 5, searchText: "Decisions True Meaning Consensus Google China hacking cyber Aurora attack" },
  { page: 159, title: "Google China Hacking Attack", chapter: 5, searchText: "China hacking attack cyber security Aurora operation human rights Gmail activists" },
  { page: 160, title: "China Decision", chapter: 5, searchText: "China decision censorship Google search human rights exit market values principles" },
  { page: 161, title: "China Decision (continued)", chapter: 5, searchText: "China decision exit market censorship human rights Google values engineers" },
  { page: 162, title: "Making Tough Decisions", chapter: 5, searchText: "tough decisions leadership consensus Google China values principles courage" },
  { page: 163, title: "Decide with Data", chapter: 5, searchText: "decide with data analytics facts evidence-based decisions measurement objective" },
  { page: 164, title: "Decide with Data (continued)", chapter: 5, searchText: "data decisions analytics measurement evidence Google approach objective truth" },
  { page: 165, title: "The Right Way to Use Data", chapter: 5, searchText: "data decisions right way analytics measurement context judgment not just numbers" },
  { page: 166, title: "Beware Bobblehead Yes", chapter: 5, searchText: "bobblehead yes false agreement consensus dissent obligation to disagree speak up" },
  { page: 167, title: "True Consensus", chapter: 5, searchText: "true consensus meaning discussion debate everyone heard best idea wins not unanimity" },
  { page: 168, title: "Consensus Not Unanimity", chapter: 5, searchText: "consensus not unanimity disagreement debate commitment decisions obligation dissent" },
  { page: 169, title: "Know When to Ring the Bell", chapter: 5, searchText: "ring the bell decisions deadlines timing leadership call enough discussion decide" },
  { page: 170, title: "Make Fewer Decisions", chapter: 5, searchText: "fewer decisions CEO delegation empowerment trust team smart creatives autonomy" },
  { page: 171, title: "Make Fewer Decisions (continued)", chapter: 5, searchText: "fewer decisions delegation empowerment leadership CEO focus important matters" },
  { page: 172, title: "Meet Every Day", chapter: 5, searchText: "meet every day staff meetings daily updates communication alignment speed issues" },
  { page: 173, title: "You're Both Right", chapter: 5, searchText: "both right conflict resolution mediation decisions disagreement find common ground" },
  { page: 174, title: "Every Meeting Needs an Owner", chapter: 5, searchText: "meeting needs owner decision maker accountability meeting management eight people" },
  { page: 175, title: "Meeting Management", chapter: 5, searchText: "meeting management effective meetings eight people rule decision maker action items" },
  { page: 176, title: "Horseback Law", chapter: 5, searchText: "horseback law quick decisions good enough Voltaire perfect enemy of the good speed" },
  { page: 177, title: "Horseback Law (continued)", chapter: 5, searchText: "horseback law decisions speed good enough imperfect action better than perfect inaction" },
  { page: 178, title: "Spend 80% on 80% of Revenue", chapter: 5, searchText: "80 percent time revenue core business focus priorities allocation resources" },
  { page: 179, title: "Succession Planning", chapter: 5, searchText: "succession planning leadership development next generation talent pipeline future" },
  { page: 180, title: "Succession Planning (continued)", chapter: 5, searchText: "succession planning leadership pipeline development talent management prepare" },
  { page: 181, title: "Coaching for Decision Making", chapter: 5, searchText: "coaching decisions Bill Campbell leadership mentorship guidance support" },
  { page: 182, title: "Eric's Self-Review", chapter: 5, searchText: "Eric self-review performance assessment leadership honest evaluation improvement" },
  { page: 183, title: "Self-Review Practice", chapter: 5, searchText: "self-review practice leadership assessment honesty improvement growth empowerment" },
  { page: 184, title: "Decision-Making Principles", chapter: 5, searchText: "decision-making principles consensus data speed meetings leadership delegation" },
  { page: 185, title: "Decisions and Leadership", chapter: 5, searchText: "decisions leadership CEO role delegation empowerment consensus meetings coaching" },
  { page: 186, title: "Decisions in Practice", chapter: 5, searchText: "decisions practice Google examples leadership consensus data measurement" },
  { page: 187, title: "Decisions at Scale", chapter: 5, searchText: "decisions scale large organization company growth management process adaptation" },
  { page: 188, title: "Obligation to Dissent", chapter: 5, searchText: "obligation to dissent disagreement speak up challenge decisions culture safety" },
  { page: 189, title: "Dissent and Debate", chapter: 5, searchText: "dissent debate decisions healthy conflict constructive disagreement best ideas win" },
  { page: 190, title: "Decisions Summary", chapter: 5, searchText: "decisions summary consensus data meetings leadership coaching delegation" },
  { page: 191, title: "Decisions Chapter Review", chapter: 5, searchText: "decisions review consensus data fewer decisions meet every day horseback law" },
  { page: 192, title: "Decisions Lessons", chapter: 5, searchText: "decisions lessons consensus data horseback law meetings coaching leadership" },
  { page: 193, title: "Decisions and Teams", chapter: 5, searchText: "decisions teams collaboration consensus leadership delegation empowerment" },
  { page: 194, title: "Decision Frameworks", chapter: 5, searchText: "decision frameworks Google approach leadership management data consensus" },
  { page: 195, title: "Decisions Chapter Closing", chapter: 5, searchText: "decisions closing consensus meaning data meetings leadership speed" },
  { page: 196, title: "Decisions Final Notes", chapter: 5, searchText: "decisions final notes consensus data leadership Google lessons learned" },
  { page: 197, title: "Decisions Conclusion", chapter: 5, searchText: "decisions conclusion consensus true meaning data leadership coaching empowerment" },
  { page: 198, title: "Decisions Wrap-Up", chapter: 5, searchText: "decisions wrap-up leadership consensus data coaching lessons Google" },
  { page: 199, title: "Communications Chapter Illustration", chapter: 5, searchText: "illustration communications chapter people router cartoon" },
  { page: 200, title: "Communications - Be a Damn Good Router", chapter: 6, searchText: "Communications Be a Damn Good Router Jonathan expensive router email information flow" },
  { page: 201, title: "Jonathan the Expensive Router", chapter: 6, searchText: "Jonathan router engineer email responsive information flow communication networking" },
  { page: 202, title: "Information Flow in Companies", chapter: 6, searchText: "information flow companies twenty-story building parsing hoarding power control balcony boss" },
  { page: 203, title: "Traditional vs Modern Information", chapter: 6, searchText: "traditional information hoarding Soviet Union James OToole Warren Bennis power knowledge shared" },
  { page: 204, title: "Information Is the Lifeblood", chapter: 6, searchText: "information lifeblood business Bill Gates knowledge shared power leadership damn good router" },
  { page: 205, title: "Default to Open", chapter: 6, searchText: "default to open share everything board report quarterly Google transparency information" },
  { page: 206, title: "Google Board Letter", chapter: 6, searchText: "board letter quarterly report share employees Eric presents slides company-wide Search Ads YouTube" },
  { page: 207, title: "Share Everything", chapter: 6, searchText: "share everything board letter redaction lawyers legal confidential transparency trust" },
  { page: 208, title: "Sharing Board Materials", chapter: 6, searchText: "sharing board materials transparency quality trust employees leaks Google 2004 public" },
  { page: 209, title: "Intranet and TGIF", chapter: 6, searchText: "Moma intranet TGIF meeting transparency demos products information sharing Willy Wonka bloggers" },
  { page: 210, title: "OKRs - Objectives and Key Results", chapter: 6, searchText: "OKRs Objectives Key Results transparency priorities alignment goals quarterly individual team" },
  { page: 211, title: "OKRs and Alignment", chapter: 6, searchText: "OKRs alignment Larry quarterly meeting grading performance red yellow marks candid failure" },
  { page: 212, title: "Know the Details", chapter: 6, searchText: "know details John Seely Brown asking questions leadership Eric management executives deliverables" },
  { page: 213, title: "Larry Knows the Truth", chapter: 6, searchText: "Larry truth Eric managers engineers information flow regurgitation parsing snippets weekly" },
  { page: 214, title: "Snippets", chapter: 6, searchText: "snippets weekly status reports Google Moma Larry engineers truth information flow activities" },
  { page: 215, title: "It Must Be Safe to Tell the Truth", chapter: 6, searchText: "safe tell truth bad news questions transparency Jonathan history class football players" },
  { page: 216, title: "Postmortems and TGIF Q&A", chapter: 6, searchText: "postmortems TGIF truth transparency Dory questions voting Larry Sergey red green paddles" },
  { page: 217, title: "Climb Confess Comply", chapter: 6, searchText: "climb confess comply transparency bad news pilots aviation trust reward honesty listening" },
  { page: 218, title: "Start the Conversation", chapter: 6, searchText: "start conversation Michael Jackson This Is It movie Mountain View theater Jonathan premiere" },
  { page: 219, title: "Importance of Conversation", chapter: 6, searchText: "conversation important laziness technology email text face-to-face open door walk through" },
  { page: 220, title: "Facilitating Conversations", chapter: 6, searchText: "facilitating conversations Urs Holzle user manual Marissa Mayer office hours tribal elders" },
  { page: 221, title: "Tribal Elders and Experts", chapter: 6, searchText: "tribal elders experts Bell Labs knowledge rock stars company connect new employees" },
  { page: 222, title: "Repetition Doesn't Spoil the Prayer", chapter: 6, searchText: "repetition doesn't spoil prayer overcommunicate leadership message twenty times Hail Mary" },
  { page: 223, title: "Overcommunicating Well", chapter: 6, searchText: "overcommunicate guidelines core themes reinforce values strategy industry sacred mission" },
  { page: 224, title: "Core Themes in Communication", chapter: 6, searchText: "core themes communication Google users first thinking big technology optimists not afraid fail" },
  { page: 225, title: "Is the Communication Effective", chapter: 6, searchText: "communication effective fresh relevant varied attention search query length 5 percent Eric memos" },
  { page: 226, title: "Interesting Fun Inspirational", chapter: 6, searchText: "communication interesting fun inspirational curious Kevin Kelly Moore's Law Wired inevitable debate" },
  { page: 227, title: "Authentic Communication", chapter: 6, searchText: "communication authentic your thoughts ideas Eric Iraq trip 2009 Jonathan daughter soccer videos" },
  { page: 228, title: "Right People and Right Media", chapter: 6, searchText: "communication right people distribution list email media channels video social networks posters" },
  { page: 229, title: "Tell the Truth and Bank Goodwill", chapter: 6, searchText: "tell truth humble goodwill rainy day trust loyalty smart creatives screw up balance" },
  { page: 230, title: "How Was London - Staff Meetings", chapter: 6, searchText: "How Was London staff meetings trip reports travel learning sharing functional rut issues" },
  { page: 231, title: "Trip Reports - Patrick Pichette", chapter: 6, searchText: "trip reports Patrick Pichette CFO London mobile phones Android finance observations business" },
  { page: 232, title: "Review Yourself", chapter: 6, searchText: "review yourself self-review management golden rule 360-degree feedback honest criticism Bill Campbell" },
  { page: 233, title: "Self-Review Process", chapter: 6, searchText: "self-review process Eric candidly failings empowerment decisions consensus impatient improving CEO" },
  { page: 234, title: "Email Wisdom", chapter: 6, searchText: "email wisdom communication rules respond quickly crisp writing inbox management foreboding Internet" },
  { page: 235, title: "Email Rules", chapter: 6, searchText: "email rules respond quickly writing crisp Elmore Leonard inbox clean OHIO act right away" },
  { page: 236, title: "Email Rules (continued)", chapter: 6, searchText: "email LIFO router forward bcc yell follow up action items track copy yourself label" },
  { page: 237, title: "Email Search and Retrieval", chapter: 6, searchText: "email search keywords future self documents passports licenses insurance cards retrieval" },
  { page: 238, title: "Have a Playbook - 1:1s", chapter: 6, searchText: "playbook 1:1s one-on-ones Bill Campbell match lists manager employee top five things problems" },
  { page: 239, title: "1:1 Format", chapter: 6, searchText: "1:1 format performance peer groups management leadership innovation sales engineering product budget" },
  { page: 240, title: "Board Meetings - Noses In Fingers Out", chapter: 6, searchText: "board meetings noses in fingers out harmony transparency advice strategy tactics lowlights" },
  { page: 241, title: "Board Meetings Execution", chapter: 6, searchText: "board meetings highlights lowlights Eric preparation honest problems challenges Google constipated" },
  { page: 242, title: "Board Presentations by Smart Creatives", chapter: 6, searchText: "board presentations product managers Jonathan smart creatives training executive communications skills" },
  { page: 243, title: "Board Focus on Strategy", chapter: 6, searchText: "board focus strategy products governance lawsuits Siebel Oracle Apple Eric voice mail" },
  { page: 244, title: "Partners - Act Like Diplomats", chapter: 6, searchText: "partners diplomats coopetition frenemy partnerships realpolitik diplomacy Kissinger China" },
  { page: 245, title: "Partnership Diplomacy", chapter: 6, searchText: "partnership diplomacy Henry Kissinger China dual constituencies external partner company interests sales" },
  { page: 246, title: "Press Interviews - Have a Conversation", chapter: 6, searchText: "press interviews conversation not message FAQs scripted Jonathan monkey trained insight" },
  { page: 247, title: "Press Conversations", chapter: 6, searchText: "press conversation messaging insight journalists criticism tension Ellen West thought leader" },
  { page: 248, title: "Relationships Not Hierarchy", chapter: 6, searchText: "relationships not hierarchy chaos organization Eric Novell Mario Andretti control running smoothly" },
  { page: 249, title: "Building Relationships", chapter: 6, searchText: "relationships people three-week rule listen trust praise Eric care family contacts" },
  { page: 250, title: "Praise and Relationships", chapter: 6, searchText: "praise underused management tool relationships deserved don't hold back smile" },
  { page: 251, title: "Communications Chapter End", chapter: 6, searchText: "communications end relationships hierarchy praise leadership router information" },
  { page: 252, title: "Communications Conclusion", chapter: 6, searchText: "communications conclusion router information open transparent share conversations" },
  { page: 253, title: "Innovation Chapter Illustration", chapter: 6, searchText: "illustration innovation chapter fish bowls dreaming cartoon" },
  { page: 254, title: "Innovation - Create the Primordial Ooze", chapter: 7, searchText: "Innovation Create Primordial Ooze Eric Steve Jobs Calafia coffee Android Apple" },
  { page: 255, title: "Eric and Steve Jobs at Calafia", chapter: 7, searchText: "Eric Steve Jobs Calafia Palo Alto Stanford Android iOS Apple intellectual property open-source" },
  { page: 256, title: "Steve Jobs and NeXT", chapter: 7, searchText: "Steve Jobs NeXT Sun Objective-C 1993 reality distortion field Eric parking lot friendship" },
  { page: 257, title: "Eric Joins Apple Board", chapter: 7, searchText: "Eric Apple board 2006 iPhone Android Andy Rubin Motorola Nokia Samsung conflicts interest" },
  { page: 258, title: "iPhone Launch and Android", chapter: 7, searchText: "iPhone 2007 launch Android YouTube video Steve Jobs iOS patent legal battles Eric board resign 2009" },
  { page: 259, title: "iOS and Android Platforms", chapter: 7, searchText: "iOS Android platforms smartphone PC Windows Microsoft innovation economic development globe" },
  { page: 260, title: "Steve Jobs Legacy", chapter: 7, searchText: "Steve Jobs legacy impact smart creative beauty science art technical artistic business computing" },
  { page: 261, title: "Apple vs Google Innovation", chapter: 7, searchText: "Apple Google innovation different approaches open closed control platforms product cycles" },
  { page: 262, title: "Android Open Platform", chapter: 7, searchText: "Android open platform Apache license Samsung HTC Motorola Internet of things tablets phones" },
  { page: 263, title: "Apple's Controlled Model", chapter: 7, searchText: "Apple control iOS App Store product presentations Steve board meetings APMs innovations" },
  { page: 264, title: "Apple's Product Culture", chapter: 7, searchText: "Apple product culture leaders technical backgrounds uber-smart creative controlled model innovation" },
  { page: 265, title: "Steve Jobs as Counterexample", chapter: 7, searchText: "Steve Jobs counterexample innovation principles instinct insights exceptional few if equal try" },
  { page: 266, title: "What Is Innovation", chapter: 7, searchText: "What is innovation Wall Street Journal 33000 times novel useful new surprising radically useful" },
  { page: 267, title: "Innovation Defined", chapter: 7, searchText: "innovation new surprising radically useful self-driving cars Knight Rider search improvements 500" },
  { page: 268, title: "Inclusive Innovation", chapter: 7, searchText: "inclusive innovation everyone innovates search team fifteen years Google[x] self-driving car" },
  { page: 269, title: "Understand Your Context", chapter: 7, searchText: "understand context Google[x] Venn diagram big challenge radical solution breakthrough technology feasible" },
  { page: 270, title: "Innovation Context - Project Loon", chapter: 7, searchText: "Project Loon helium balloons broadband Internet five billion people feasible technology 20km" },
  { page: 271, title: "Big Markets for Innovation", chapter: 7, searchText: "big markets innovation competition growth Gmail Paul Buchheit email browser-based features" },
  { page: 272, title: "The CEO Needs to Be the CIO", chapter: 7, searchText: "CEO CIO Chief Innovation Officer Udi Manber Yahoo innovation bureaucracy council oxymoron left" },
  { page: 273, title: "Innovation Cannot Be Managed", chapter: 7, searchText: "innovation managed Darwin natural selection ideas primordial ooze evolution Origin of Species allowed" },
  { page: 274, title: "Creating a Culture of Ooze", chapter: 7, searchText: "culture ooze Thomas Edison Bell Labs Xerox PARC Internet Darwinian speed testing prototypes" },
  { page: 275, title: "First Followers and Innovation", chapter: 7, searchText: "first followers Derek Sivers TED talk dancing hill lone nut leader movement innovative Robert Noyce" },
  { page: 276, title: "Focus on the User", chapter: 7, searchText: "focus user search engineers prototype results typing speed Google Instant return key" },
  { page: 277, title: "Google Instant", chapter: 7, searchText: "Google Instant search results typing prototype launch organic paid search teams speed" },
  { page: 278, title: "User Focus and Revenue", chapter: 7, searchText: "Google Instant revenue question financial analysis Jonathan launch user focus no ROI analysis" },
  { page: 279, title: "Knowledge Graph and Panda", chapter: 7, searchText: "Knowledge Graph 2012 Panda algorithm quality ads revenue user trust product excellence" },
  { page: 280, title: "Focus on User All Else Follows", chapter: 7, searchText: "focus user all else follows trust revenue confidence Larry Sergey IPO letter priority" },
  { page: 281, title: "Keyhole and Google Earth", chapter: 7, searchText: "Keyhole Google Earth Jonathan Jeff Huber Sergey Brin acquisition board field trip maps" },
  { page: 282, title: "Google Earth Toolbar and Sundar Pichai", chapter: 7, searchText: "Google Earth Toolbar Sundar Pichai Urs Holzle revenue download browser search ads money follows" },
  { page: 283, title: "Motorola User vs Customer Focus", chapter: 7, searchText: "Motorola acquisition user focus customer carriers Verizon AT&T product review phones users partners" },
  { page: 284, title: "Think Big", chapter: 7, searchText: "think big Vint Cerf interplanetary Internet space network protocols twenty-five years" },
  { page: 285, title: "Think Big - Pasteur's Quadrant", chapter: 7, searchText: "think big Regina Dugan DARPA Pasteur's Quadrant basic science real-world 10X Larry Page" },
  { page: 286, title: "10X Thinking", chapter: 7, searchText: "10X thinking Larry Page Astro Teller Google[x] 10 percent tweak 500 miles per gallon start over" },
  { page: 287, title: "Big Bets vs Mediocrity", chapter: 7, searchText: "big bets Motorola Dennis Woodside dozens phones mediocrity market segments iPhone Apple Lenovo" },
  { page: 288, title: "Big Challenges Attract Big Talent", chapter: 7, searchText: "big challenges talent Rosabeth Moss Kanter human capital skills connections 10X job offers" },
  { page: 289, title: "Mike Cassidy and Project Loon", chapter: 7, searchText: "Mike Cassidy Ruba Direct Hit Project Loon Google[x] helium balloons aerospace retention" },
  { page: 290, title: "10Xing Is Contagious", chapter: 7, searchText: "10Xing contagious Larry audacious projects salespeople lawyers financial folks recruiting retention moon" },
  { page: 291, title: "Set Almost Unattainable Goals", chapter: 7, searchText: "unattainable goals OKRs 1999 John Doerr Kleiner Perkins Andy Grove Intel management by objectives" },
  { page: 292, title: "OKR Characteristics", chapter: 7, searchText: "OKR measurable key results stretch goals ambitious 70 percent scoring Jupiter data center Google+" },
  { page: 293, title: "OKRs - Scoring and Competition", chapter: 7, searchText: "OKRs scoring honest performance teams individuals not comprehensive focus not chasing competitors" },
  { page: 294, title: "70/20/10 Resource Allocation", chapter: 7, searchText: "70/20/10 resource allocation yes culture people headcount crazy project antibodies no framework" },
  { page: 295, title: "70/20/10 - Sergey's Buckets", chapter: 7, searchText: "70/20/10 Sergey buckets 2002 top-100 list core search ads emerging new high-risk big payoff" },
  { page: 296, title: "Overinvesting and Apple Newton", chapter: 7, searchText: "70/20/10 overinvesting Apple Newton confirmation bias sunk costs handwriting recognition Motorola" },
  { page: 297, title: "Constraints Breed Creativity", chapter: 7, searchText: "ten percent constraints creativity Henry Ford pictures frames sonnets fourteen lines ingenuity" },
  { page: 298, title: "Google Books and Street View", chapter: 7, searchText: "Google Books 2002 Larry Page 129 million books digitize camera Marissa Mayer Street View Sergey" },
  { page: 299, title: "20 Percent Time", chapter: 7, searchText: "20 percent time 2004 Kevin Gibbs Google Suggest autocomplete prototype email real-time completion" },
  { page: 300, title: "Google Suggest and First Followers", chapter: 7, searchText: "Google Suggest 20 percent first followers Derek Sivers engineers joined prototype global billions" },
  { page: 301, title: "20 Percent Time - Freedom Not Time", chapter: 7, searchText: "20 percent time freedom Google Now News Maps Steve Jobs hierarchy ideas 120 percent nights weekends" },
  { page: 302, title: "Street View Trike", chapter: 7, searchText: "Street View trike Dan Ratner Barcelona Spain alleyways snowmobiles Vancouver Olympics museums pushcarts" },
  { page: 303, title: "Gmail Creation - Paul Buchheit", chapter: 7, searchText: "Gmail Paul Buchheit Caribou 20 percent project email ads AdWords combinatorial innovation hacked" },
  { page: 304, title: "Gmail Ads Become AdSense", chapter: 7, searchText: "Gmail ads AdSense Paul Buchheit insubordination Williams-Sonoma multibillion-dollar technology refined" },
  { page: 305, title: "Bringing Ideas to Fruition", chapter: 7, searchText: "ideas fruition prototype Darwinian process collaborators 20 percent peers excited team" },
  { page: 306, title: "Demo Days", chapter: 7, searchText: "demo days prototypes week science-fair open house Linus Pauling ideas fail Steve Jobs NeXT ecosystem" },
  { page: 307, title: "Learning from 20 Percent Projects", chapter: 7, searchText: "learning 20 percent skills collaboration Urs Holzle best educational program smart creatives new" },
  { page: 308, title: "Jonathan's Favorite - Yad Vashem", chapter: 7, searchText: "Jonathan favorite 20 percent Yad Vashem Holocaust Jerusalem museum Israel digitize online survivors" },
  { page: 309, title: "Open Gallery and Google Cultural Institute", chapter: 7, searchText: "Open Gallery Yossi Matias Larry Sergey Yad Vashem museums Google Cultural Institute Acropolis" },
  { page: 310, title: "Ideas Come from Anywhere", chapter: 7, searchText: "ideas come anywhere suggestion box William Denny 1880 National Cash Register Marissa Mayer Gong Show" },
  { page: 311, title: "Ideas from Outside - User Innovation", chapter: 7, searchText: "ideas outside users volunteers translate Map Maker Google Pakistan Craig Nevill-Manning Beer Demos" },
  { page: 312, title: "Ship and Iterate", chapter: 7, searchText: "ship and iterate Voltaire perfect enemy good Steve Jobs real artists ship launch improve AdWords" },
  { page: 313, title: "Ship and Iterate - Chrome and AdWords", chapter: 7, searchText: "AdWords ship iterate Chrome 2008 minimal marketing seventy million users TV advertising quality" },
  { page: 314, title: "Iterating Well", chapter: 7, searchText: "iterate well not crummy products limit functionality wow feature Eric 2006 launch expand" },
  { page: 315, title: "Ship and Iterate for Digital Products", chapter: 7, searchText: "ship iterate digital software 3D printing automobile chip prototypes user data virtual experience" },
  { page: 316, title: "Fail Well - Google Wave", chapter: 7, searchText: "fail well Google Wave 2009 Sydney 20 percent email communication platform protocols flop canceled" },
  { page: 317, title: "Wave Failed Well", chapter: 7, searchText: "Wave failed quickly not stigmatized recruited internally Google+ Gmail morph ideas Nassim Taleb antifragile" },
  { page: 318, title: "Timing of Failure", chapter: 7, searchText: "timing failure fast fail iterate metrics Jeff Bezos Amazon long time horizon self-driving cars Google Fiber" },
  { page: 319, title: "It's Not About Money", chapter: 7, searchText: "not about money 20 percent intrinsic rewards Hurricane Katrina 2005 Google Earth NOAA Crisis Response Google.org" },
  { page: 320, title: "Conclusion - Imagine the Unimaginable", chapter: 8, searchText: "Conclusion Imagine Unimaginable Eric 2013 vacation kids videos tablet TV dark streaming apps" },
  { page: 321, title: "Technology Disruption and Anxiety", chapter: 8, searchText: "technology disruption optimism anxiety recession jobs skills training pressure economic middle-class" },
  { page: 322, title: "From Downton Abbey to Diapers.com", chapter: 8, searchText: "Downton Abbey Diapers.com economic transition Household Corporation Platform feudal industrial" },
  { page: 323, title: "The Rise of Platforms", chapter: 8, searchText: "platforms Corporation Platform Amazon General Motors Diapers.com consumers marketplace buyers sellers voice" },
  { page: 324, title: "Who Succeeds and Fails in Platforms", chapter: 8, searchText: "succeeds fails platforms Borders bankruptcy Amazon $1.6 billion Chapter 11 incumbent businesses" },
  { page: 325, title: "Alternative for Incumbents", chapter: 8, searchText: "incumbents alternative strategy platforms smart creatives Vinod Khosla Stanford risk-averse BlackBerry" },
  { page: 326, title: "The Social Web and Facebook", chapter: 8, searchText: "social web Facebook Web 1.0 2.0 browser HTML broadband Friendster Myspace Twitter Digg Orkut" },
  { page: 327, title: "Google and Social - Wave Buzz", chapter: 8, searchText: "Google social Orkut Wave Buzz Facebook Vic Gundotra Bradley Horowitz mobile first 0 for 2" },
  { page: 328, title: "Google+ and Emerald Sea", chapter: 8, searchText: "Google+ Emerald Sea Vic Gundotra Bradley Horowitz social platform AdWords YouTube disruption job" },
  { page: 329, title: "Ask the Hardest Questions", chapter: 8, searchText: "hardest questions future business Clayton Christensen innovation entropy what do you see" },
  { page: 330, title: "Sun Microsystems - Hard Questions", chapter: 8, searchText: "Sun Microsystems Wintel PCs Intel Windows Eric Owen Brown Scott McNealy price-performance $141 billion Oracle" },
  { page: 331, title: "Hard Questions in Ongoing Companies", chapter: 8, searchText: "hard questions companies uncomfortable Samuel Johnson Larry Page CEO five years prediction imagination" },
  { page: 332, title: "Imagine What Could Be True", chapter: 8, searchText: "imagine could be true Vinod Khosla 1980 microprocessors 1990 cellular phones 1995 Internet self-driving car" },
  { page: 333, title: "Hard Questions to Ask Your Business", chapter: 8, searchText: "competitor attack platforms disruption cannibalization revenue technical insights product people hiring" },
  { page: 334, title: "More Hard Questions", chapter: 8, searchText: "hiring C-suite executives decisions freedom innovative employees information hoarders routers silos profit" },
  { page: 335, title: "Attracting Smart Creatives - Location", chapter: 8, searchText: "attracting smart creatives location Silicon Valley business hubs clusters technology physical matters" },
  { page: 336, title: "Global Innovation Hubs", chapter: 8, searchText: "hubs finance New York London Frankfurt fashion Paris Milan entertainment LA Mumbai diamonds biotech Boston" },
  { page: 337, title: "The Role of Government", chapter: 8, searchText: "government incumbents disruption innovation regulation education K-12 lifelong digital infrastructure immigration" },
  { page: 338, title: "Government and Innovation", chapter: 8, searchText: "government innovation immigration freedom regulations Tesla self-driving cars red flag law accidents data" },
  { page: 339, title: "Big Problems Are Information Problems", chapter: 8, searchText: "big problems information technology optimists Matrix Star Trek McCoy data computing power playground" },
  { page: 340, title: "Data Explosion and Collaboration", chapter: 8, searchText: "data explosion collaboration scientists Carl Shapiro Hal Varian Information Rules Fusion Tables silos" },
  { page: 341, title: "Speed and General Purpose Technologies", chapter: 8, searchText: "speed latency general purpose technologies steam engine Watt 1763 Netscape 1994 Excite@Home cable modems" },
  { page: 342, title: "Collective Intelligence", chapter: 8, searchText: "collective intelligence Garry Kasparov 1997 Deep Blue IBM chess computers grandmasters collaboration" },
  { page: 343, title: "The Future Is Bright - Healthcare", chapter: 8, searchText: "future bright health care sensors genetic analysis risk factors hospital information transparency costs" },
  { page: 344, title: "Future of Transportation and Finance", chapter: 8, searchText: "transportation self-driving cars ownership insurance auto data distance location financial customized" },
  { page: 345, title: "Creative Industries and Technology", chapter: 8, searchText: "creative industries content media House of Cards Game of Thrones Internet fragmented CGI storytelling" },
  { page: 346, title: "Technology Transforms Every Pursuit", chapter: 8, searchText: "technology transforms crime agriculture pharmaceuticals defense energy aerospace education smart creatives believe" },
  { page: 347, title: "The Next Smart Creative", chapter: 8, searchText: "next smart creative forces change relearn technology generation landline date movies broadband" },
  { page: 348, title: "The Next Smart Creative (continued)", chapter: 8, searchText: "next smart creative garage dorm room Google irrelevant inevitable no business wins forever inspiring chilling" },
  { page: 349, title: "Conclusion Illustration", chapter: 8, searchText: "illustration conclusion running people cartoon generations change" },
  { page: 350, title: "Acknowledgments", chapter: 8, searchText: "Acknowledgments Larry Page Sergey Brin Google founders culture strategy hiring excellence" },
  { page: 351, title: "Acknowledgments (continued)", chapter: 8, searchText: "Ann Hiatt Brian Thompson Kim Cooper Pam Shore Scott Rubin Rachel Whetstone Kent Walker Marc Ellenbogen" },
  { page: 352, title: "Acknowledgments (continued)", chapter: 8, searchText: "Dennis Woodside Urs Holzle Alison Cormack Jared Cohen Laszlo Bock Nikesh Arora" },
  { page: 353, title: "Acknowledgments (continued)", chapter: 8, searchText: "Susan Wojcicki Salar Kamangar Marissa Mayer Sundar Pichai Lorraine Twohill Clay Bavor Brian Rakowski" },
  { page: 354, title: "Acknowledgments (continued)", chapter: 8, searchText: "Colin McMillen Prem Ramaswami Devin Ivester Hal Varian Alan Eustace Shona Brown David Drummond" },
  { page: 355, title: "Acknowledgments (continued)", chapter: 8, searchText: "Bill Campbell John Doerr Mike Moritz Ram Shriram John Hennessy Art Levinson Paul Otellini board members" },
  { page: 356, title: "Acknowledgments - Family", chapter: 0, searchText: "Jonathan family Beryl Joshua Hannah Rina Rosenberg Nathan Rosenberg Karen Gordon David siblings" },
  { page: 357, title: "Acknowledgments - Contributors", chapter: 0, searchText: "Dr Lorne Rosenfield Lauren Dan Chung Matt Pyken Glenn Yeffeth BenBella Adam Grosser professors" },
  { page: 358, title: "Acknowledgments - Mentors", chapter: 0, searchText: "Jeff Ullman Princeton Bill Joy Sue Graham Bob Fabry Berkeley Bell Labs Mike Lesk Al Aho Unix" },
  { page: 359, title: "Acknowledgments - Colleagues", chapter: 0, searchText: "Jim Morris Butler Lampson Bob Taylor Roy Levin Xerox PARC Scott McNealy Vinod Khosla Sun Novell" },
  { page: 360, title: "Acknowledgments - Team", chapter: 0, searchText: "Peter Wendell Stanford Nishant Choksi illustrations Melissa Thomas Marina Krakovsky David Javerbaum humor" },
  { page: 361, title: "Acknowledgments - Alan Eagle", chapter: 0, searchText: "Jim Levine agent John Brodie editor Galaxy Game Stanford Tresidder Alan Eagle coauthor Gunn High" },
  { page: 362, title: "A Note About the Authors - Eric Schmidt", chapter: 0, searchText: "Eric Schmidt Google 2001 CEO executive chairman Novell Sun Microsystems Princeton Berkeley" },
  { page: 363, title: "About Jonathan Rosenberg and Alan Eagle", chapter: 0, searchText: "Jonathan Rosenberg SVP Google 2000 Excite@Home Apple Alan Eagle 2007 communications Dartmouth Wharton" },
  { page: 364, title: "Also by Eric Schmidt", chapter: 0, searchText: "Also Eric Schmidt New Digital Age Reshaping Future People Nations Business Jared Cohen" },
  { page: 365, title: "Glossary", chapter: 0, searchText: "Glossary AdSense AdWords ahcharye Android API APM cloud computing Coase law Dory Excite@Home" },
  { page: 366, title: "Glossary (continued)", chapter: 0, searchText: "Glossary Googlegeist Google[x] HiPPO learning animals market cap Memegen Moma Moore's Law" },
  { page: 367, title: "Glossary (continued)", chapter: 0, searchText: "Glossary multisided market Noogler obligation dissent OKR open open-source payback period platform ROI" },
  { page: 368, title: "Glossary (continued)", chapter: 0, searchText: "Glossary scale smart creative tenureocracies TGIF user interface Wave Web 2.0" },
  { page: 369, title: "Notes - Introduction", chapter: 0, searchText: "Notes Pam troubled warm smile Oxford English Dictionary Google verb Finland code name" },
  { page: 370, title: "Notes (continued)", chapter: 0, searchText: "Notes Microsoft Secrets Overdrive Bill Gates How Web Was Won Silicon Valley entrepreneurs funding" },
  { page: 371, title: "Notes (continued)", chapter: 0, searchText: "Notes Susan Wojcicki landlord focus user Peter Drucker Practice Management Steve Ballmer reorg" },
  { page: 372, title: "Notes (continued)", chapter: 0, searchText: "Notes mountain data cloud computing downward cost curve George Gilder Gilder Paradigm bandwidth Wired" },
  { page: 373, title: "Notes (continued)", chapter: 0, searchText: "Notes Peter Drucker Landmarks Tomorrow gender pronouns Schopenhauer Essays Aphorisms" },
  { page: 374, title: "Notes - Culture", chapter: 0, searchText: "Notes Culture Coach Wooden UCLA leadership learning championships basketball fifteen years" },
  { page: 375, title: "Notes (continued)", chapter: 0, searchText: "Notes Culture Strategy references citations sources chapters" },
  { page: 376, title: "Notes - Strategy and Talent", chapter: 0, searchText: "Notes Strategy Talent references citations Bezos Forbes leadership" },
  { page: 377, title: "Notes - Talent", chapter: 0, searchText: "Notes Talent hiring references citations sources committees" },
  { page: 378, title: "Notes - Decisions", chapter: 0, searchText: "Notes Decisions consensus references citations sources China hacking" },
  { page: 379, title: "Notes - Communications", chapter: 0, searchText: "Notes Communications router references citations sources email OKRs" },
  { page: 380, title: "Notes - Innovation", chapter: 0, searchText: "Notes Innovation ooze 20 percent references citations Android Apple Steve Jobs" },
  { page: 381, title: "Notes - Innovation (continued)", chapter: 0, searchText: "Notes Innovation Conclusion references citations ship iterate fail" },
  { page: 382, title: "Notes - Conclusion", chapter: 0, searchText: "Notes Conclusion references Vinod Khosla platforms disruption imagine unimaginable" },
  { page: 383, title: "Notes (continued)", chapter: 0, searchText: "Notes references citations sources continued endnotes" },
  { page: 384, title: "Notes End", chapter: 0, searchText: "Notes end final references citations copyright" }
];
